### ISSUE TITLE
TypeError: this.handlers[[satoriResult.match,this.alexa.handler.state].join(...)].call is not a function

### ISSUE THREAD

**Issue by hideokamoto** [voice-assistant/kuchimane#5]
I've try to use the library to test my Alexa skill, but I saw some error.
repo: https://github.com/hideokamoto/alexa-test-practice/tree/kuchimane

```
$ node -v
v10.1.0
```

## Reproduce

```
$ git clone git@github.com:hideokamoto/alexa-test-practice.git
$ cd alexa-test-practice/lambda/custom
$ npm i
$ npm test

  4 passing (16ms)
  1 failing

  1) e2e
       greet:
     TypeError: this.handlers[[satoriResult.match,this.alexa.handler.state].join(...)].call is not a function
      at Kuchimane.listen (node_modules/kuchimane/dist/bundle.js:145:83)
      at /Users/dc_hideokamoto/develop/node/alexa/unit-test/lambda/custom/node_modules/kuchimane/dist/bundle.js:150:58
      at Context.it (tests/e2e/index.test.js:15:7)
```

## test code

```
const kuchimane = require('kuchimane')
const Kuchimane = kuchimane.default
const assert = require('power-assert')
const LaunchRequest = require('../../handlers/LaunchRequest')
const HelloWorldIntent = require('../../handlers/HelloWorldIntent')

const kuchimaneRunner = Kuchimane.runner({ LaunchRequest, HelloWorldIntent }, `${__dirname}/kuchimane_config.json`)

describe('e2e', () => {
  it('greet', () => {
    return kuchimaneRunner.talkCheck('Open greeter', (replyMessage) => {
      console.log(replyMessage)
      assert.deepEqual(replyMessage, 'Welocome to GreetingBot')
    })()
      .then(kuchimaneRunner.talkCheck('Hello', (replyMessage) => {
        assert.deepEqual(replyMessage, 'Hello! Good day')
      }))
  })
})
```

**Comment by hideokamoto** [comment]
probably ...
Is the lib only supports `alexa-sdk` ?
I'm using `ask-sdk` and I saw the issue.

**Comment by kikaineko** [comment]
Thank you for your issue.

We follow the `ask-sdk v1`, but the last version of the `ask-sdk` is two.
They are completely different, you know.
Now we do not follow `v2` yet, sorry.
